# Generated by Django 4.0.4 on 2022-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milestones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestonestable",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "NOT_STARTED"),
                    (1, "IN_PROGRESS"),
                    (2, "COMPLETED"),
                    (3, "BLOCKED"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
